<a href="https://colab.research.google.com/github/yuvids2050/class-practice/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Dataset Creation
---



In [3]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

In [ ]:
# Question 1: Array Dimensions
# The finance manager wants to confirm how many stores and product categories are present in the data.

# Write NumPy code to display:

# Number of dimensions in sales_data
# Shape of sales_data
# Total number of values
# Data type of the array
# Memory occupied by the array
print("Number of dimensions:", sales_data.ndim)
print("Shape:", sales_data.shape)
print("Total values:", sales_data.size)
print("Data type:", sales_data.dtype)
print("Memory occupied:", sales_data.nbytes, "bytes")

Number of dimensions: 2
Shape: (5, 6)
Total values: 30
Data type: int64
Memory occupied: 240 bytes


In [ ]:
# Question 2: Store and Category Count
# Calculate the following:

# Total number of stores
# Total number of product categories
# Total number of store-category combinations
total_stores = len(stores)
total_categories = len(categories)
total_combinations = sales_data.size

print("Total stores:", total_stores)
print("Total categories:", total_categories)
print("Total combinations:", total_combinations)

Total stores: 5
Total categories: 6
Total combinations: 30


In [ ]:
# Question 3: Sales Data Type Conversion
# The reporting application requires sales values in floating-point format.

# Convert sales_data into:

# float32
# float64
# Compare the memory used by both arrays.
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("Float32:")
print(sales_float32)

print("\nFloat64:")
print(sales_float64)

print("\nFloat32 memory:", sales_float32.nbytes, "bytes")
print("Float64 memory:", sales_float64.nbytes, "bytes")

Float32:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]

Float64:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]

Float32 memory: 120 bytes
Float64 memory: 240 bytes


Part 3: Indexing and Data Extraction

In [ ]:
# Question 4: Bengaluru Store Analysis
# The Bengaluru regional manager wants to review sales for all product categories.

# Extract and display the complete sales row for Bengaluru.
bengaluru_sales = sales_data[0]

print("Bengaluru Sales:")
print(bengaluru_sales)

Bengaluru Sales:
[850000 420000 310000 275000 190000 225000]


In [ ]:
# Question 5: Mumbai Cost Analysis
# Extract the total cost incurred by the Mumbai store for all product categories.
mumbai_cost = cost_data[3]

print("Mumbai cost by category:")
print(mumbai_cost)

Mumbai cost by category:
[790000 390000 265000 250000 165000 205000]


In [ ]:
# Question 6: Electronics Sales Across Stores
# The electronics department wants to compare its sales performance across all five stores.

# Extract the Electronics sales column from sales_data.
electronics_sales = sales_data[:, 0]

print("Electronics Sales:")
print(electronics_sales)

Electronics Sales:
[ 850000  780000  920000 1050000  690000]


In [ ]:
# Question 7: Clothing Cost Across Stores
# Extract the Clothing cost for every store from cost_data.
clothing_cost = cost_data[:, 2]

print("Clothing Cost:")
print(clothing_cost)

Clothing Cost:
[220000 210000 245000 265000 205000]


In [ ]:
# Question 8: Hyderabad Furniture Performance
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit
furniture_sales = sales_data[1, 3]
furniture_cost = cost_data[1, 3]
furniture_profit = furniture_sales - furniture_cost

print("Furniture Sales:", furniture_sales)
print("Furniture Cost:", furniture_cost)
print("Furniture Profit:", furniture_profit)

Furniture Sales: 310000
Furniture Cost: 225000
Furniture Profit: 85000


In [ ]:
# Question 9: Chennai Category Range
# Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.
chennai_sales = sales_data[2, 1:4]

print("Chennai Groceries, Clothing, Furniture Sales:")
print(chennai_sales)

Chennai Groceries, Clothing, Furniture Sales:
[390000 340000 260000]


In [ ]:
# Question 10: Selected Store Analysis
# Extract sales data for:

# Bengaluru
# Chennai
# Pune
# Include only:

# Electronics
# Clothing
# Beauty
# Use advanced indexing.
selected_sales = sales_data[
    np.ix_([0, 2, 4], [0, 2, 4])
]

print("Selected Sales:")
print(selected_sales)

Selected Sales:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation

In [ ]:
# Question 11: Company-Wide Sales
# Calculate the total sales revenue generated by all stores and all categories.
total_sales = np.sum(sales_data)

print("Total Company Sales:", total_sales)

Total Company Sales: 11675000


In [ ]:
# Question 12: Store-Wise Sales
# Calculate total sales revenue for each store.

# Display the result together with the store names.

# Expected output format:

# Bengaluru: total sales
# Hyderabad: total sales
# Chennai: total sales
# Mumbai: total sales
# Pune: total sales
store_sales = np.sum(sales_data, axis=1)

for store, total in zip(stores, store_sales):
    print(f"{store}: {total}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


In [ ]:
# Question 13: Category-Wise Sales
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.
category_sales = np.sum(sales_data, axis=0)

for category, total in zip(categories, category_sales):
    print(f"{category}: {total}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


In [ ]:
# Question 14: Average Sales Per Store
# Calculate the average sales generated by each store across all six product categories.
store_sales = np.mean(sales_data, axis=1)

for store, average in zip(stores, store_sales):
    print(f"{store}: {average}")

Bengaluru: 378333.3333333333
Hyderabad: 382500.0
Chennai: 385000.0
Mumbai: 470000.0
Pune: 330000.0


In [ ]:
# Question 15: Average Sales Per Category
# Calculate the average sales of each product category across the five stores.
category_sales = np.mean(sales_data,axis=0)

for category, average in zip(categories, category_sales):
  print(f"{category}: {average}")


Electronics: 858000.0
Groceries: 437000.0
Clothing: 320000.0
Furniture: 283000.0
Beauty: 202000.0
Sports: 235000.0


In [ ]:
# Question 16: Highest-Selling Store
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().
store_sales = np.sum(sales_data, axis=1)

highest_index = np.argmax(store_sales)

print("Index:", highest_index)
print("Store:", stores[highest_index])
print("Total Sales:", store_sales[highest_index])


Index: 3
Store: Mumbai
Total Sales: 2820000


In [4]:
# Question 17: Lowest-Selling Store
# Identify the store with the lowest overall sales.

# Use np.argmin()
import numpy as np

store_sales = np.sum(sales_data, axis=1)

lowest_index = np.argmin(store_sales)

print("Index:", lowest_index)
print("Store:", stores[lowest_index])
print("Total Sales:", store_sales[lowest_index])

Index: 4
Store: Pune
Total Sales: 1980000


In [5]:
# Question 18: Highest-Selling Category
# Find the product category that generated the highest total sales across the company.
category_sales = np.sum(sales_data, axis=0)

highest_category_index = np.argmax(category_sales)

print("Index:", highest_category_index)
print("Category:", categories[highest_category_index])
print("Total Sales:", category_sales[highest_category_index])


Index: 0
Category: Electronics
Total Sales: 4290000


In [ ]:
# Question 19: Lowest-Selling Category
# Find the product category with the lowest total sales across all stores.

# category_sales = np.sum(sales_data, axis=0)

lowest_category_index = np.argmin(category_sales)

print("Index:", lowest_category_index)
print("Category:", categories[lowest_category_index])
print("Total Sales:", category_sales[lowest_category_index])

Part 5: Cost Analysis

In [6]:
# Question 20: Total Company Cost
# Calculate the total cost incurred by SmartMart across all stores and product categories.
total_cost = np.sum(cost_data)

print("Total Company Cost:", total_cost)

Total Company Cost: 8600000


In [7]:
# Question 21: Store-Wise Cost
# Calculate the total cost incurred by each store.

store_cost = np.sum(cost_data, axis=1)

for store, cost in zip(stores, store_cost):
    print(f"{store}: {cost}")

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


In [8]:
# Question 22: Category-Wise Cost
# Calculate the total cost incurred for each product category across all stores.

category_cost = np.sum(cost_data, axis=0)

for category, cost in zip(categories, category_cost):
    print(f"{category}: {cost}")

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


In [9]:
# Question 23: Most Expensive Store
# Identify the store with the highest total operating cost.
store_cost = np.sum(cost_data, axis=1)

index = np.argmax(store_cost)

print("Store:", stores[index])
print("Total Cost:", store_cost[index])

Store: Mumbai
Total Cost: 2065000


In [10]:
# Question 24: Lowest-Cost Store
# Identify the store with the lowest total cost.
store_cost = np.sum(cost_data, axis=1)

index = np.argmin(store_cost)

print("Store:", stores[index])
print("Total Cost:", store_cost[index])

Store: Pune
Total Cost: 1475000


In [11]:

# Question 25: Most Expensive Product Category
# Determine which product category has the highest total cost across all stores.
category_cost = np.sum(cost_data, axis=0)

index = np.argmax(category_cost)

print("Category:", categories[index])
print("Total Cost:", category_cost[index])

Category: Electronics
Total Cost: 3250000


Part 6: Profit Analysis Using Two Arrays

In [12]:
# Question 26: Profit Matrix
# Calculate the profit generated for every store and product category.

# Use:

# profit_data = sales_data - cost_data
# Display the complete profit matrix.
profit_data = sales_data - cost_data

print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [13]:
# Question 27: Store-Wise Profit
# Calculate the total profit generated by each store.
profit_data = sales_data - cost_data

store_profit = np.sum(profit_data, axis=1)

for store, profit in zip(stores, store_profit):
    print(f"{store}: {profit}")

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


In [14]:
# Question 28: Category-Wise Profit
# Calculate the total profit generated by each product category.
profit_data = sales_data - cost_data

category_profit = np.sum(profit_data, axis=0)

for category, profit in zip(categories, category_profit):
    print(f"{category}: {profit}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


In [15]:
# Question 29: Most Profitable Store
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit
profit_data = sales_data - cost_data

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

index = np.argmax(store_profit)

print("Store:", stores[index])
print("Total Sales:", store_sales[index])
print("Total Cost:", store_cost[index])
print("Total Profit:", store_profit[index])

Store: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


In [16]:
# Question 30: Least Profitable Store
# Identify the store that generated the lowest total profit.
profit_data = sales_data - cost_data

store_profit = np.sum(profit_data, axis=1)

index = np.argmin(store_profit)

print("Store:", stores[index])
print("Total Profit:", store_profit[index])

Store: Pune
Total Profit: 505000


In [17]:
# Question 31: Most Profitable Category
# Find the category with the highest total profit across all stores.
profit_data = sales_data - cost_data

category_profit = np.sum(profit_data, axis=0)

index = np.argmax(category_profit)

print("Category:", categories[index])
print("Total Profit:", category_profit[index])



Category: Electronics
Total Profit: 1040000


In [18]:
# Question 32: Least Profitable Category
# Find the category with the lowest total profit.
profit_data = sales_data - cost_data

category_profit = np.sum(profit_data, axis=0)

index = np.argmin(category_profit)

print("Category:", categories[index])
print("Total Profit:", category_profit[index])

Category: Sports
Total Profit: 340000


In [19]:
# Question 33: Maximum Individual Profit
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().
profit_data = sales_data - cost_data

index = np.argmax(profit_data)

row, column = np.unravel_index(index, profit_data.shape)

print("Profit:", profit_data[row, column])
print("Store:", stores[row])
print("Category:", categories[column])

Profit: 260000
Store: Mumbai
Category: Electronics


In [20]:
# Question 34: Minimum Individual Profit
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.
profit_data = sales_data - cost_data

index = np.argmin(profit_data)

row, column = np.unravel_index(index, profit_data.shape)

print("Profit:", profit_data[row, column])
print("Store:", stores[row])
print("Category:", categories[column])

Profit: 55000
Store: Pune
Category: Furniture


Part 7: Profit Margin Analysis

In [28]:
# Question 35: Profit Margin Matrix
# Calculate the profit margin percentage for every store-category combination.

# Use:

# profit_margin = (profit_data / sales_data) * 100
# Round the result to two decimal places
profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100

profit_margin = np.round(profit_margin, 2)

print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [29]:
# Question 36: Store-Wise Profit Margin
# Calculate the overall profit margin percentage for each store using:

# Store Profit Margin =
# Total Store Profit / Total Store Sales × 100
store_sales = np.sum(sales_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

store_margin = (store_profit / store_sales) * 100

store_margin = np.round(store_margin, 2)

for store, margin in zip(stores, store_margin):
    print(f"{store}: {margin}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


In [30]:
# Question 37: Category-Wise Profit Margin
# Calculate the overall profit margin percentage for each product category.
category_sales = np.sum(sales_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

category_margin = (category_profit / category_sales) * 100

category_margin = np.round(category_margin, 2)

for category, margin in zip(categories, category_margin):
    print(f"{category}: {margin}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


In [31]:
# Question 38: Best Store by Profit Margin
# Identify the store with the highest overall profit margin.
store_sales = np.sum(sales_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

store_margin = (store_profit / store_sales) * 100

index = np.argmax(store_margin)

print("Best Store:", stores[index])
print("Profit Margin:", round(store_margin[index], 2), "%")

Best Store: Mumbai
Profit Margin: 26.77 %


In [32]:
# Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.
category_sales = np.sum(sales_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

category_margin = (category_profit / category_sales) * 100

index = np.argmax(category_margin)

print("Best Category:", categories[index])
print("Profit Margin:", round(category_margin[index], 2), "%")

Best Category: Beauty
Profit Margin: 34.16 %


In [35]:
# Question 40: Low-Margin Transactions
# Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.
profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100

condition = profit_margin < 22

rows, columns = np.where(condition)

for row, column in zip(rows, columns):
    print(
        "Store:", stores[row],
        "| Category:", categories[column],
        "| Sales:", sales_data[row, column],
        "| Cost:", cost_data[row, column],
        "| Profit:", profit_data[row, column],
        "| Margin:", round(profit_margin[row, column], 2), "%"
    )

Part 8: Boolean Filtering

In [34]:
# Question 41: High Sales Values
# Find all sales values greater than ₹5,00,000.
high_sales = sales_data[sales_data > 500000]

print(high_sales)

[ 850000  780000  920000 1050000  510000  690000]


In [36]:
# Question 42: Low Sales Values
# Find all sales values below ₹2,00,000.

low_sales = sales_data[sales_data < 200000]

print(low_sales)


[190000 185000 175000]


In [37]:
# Question 43: High Profit Values
# Find all store-category combinations where profit is greater than ₹1,50,000.
high_profit = profit_data[profit_data > 150000]

print(high_profit)

[210000 190000 220000 260000 160000]


In [38]:
# Question 44: Moderate Sales Range
# Find sales values between ₹2,50,000 and ₹5,00,000.

# Use np.logical_and().
condition = np.logical_and(
    sales_data >= 250000,
    sales_data <= 500000
)

moderate_sales = sales_data[condition]

print(moderate_sales)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [39]:
# Question 45: Premium Performance
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.
condition = np.logical_and(
    sales_data > 500000,
    profit_data > 150000
)

rows, columns = np.where(condition)

for row, column in zip(rows, columns):
    print(
        "Store:", stores[row],
        "| Category:", categories[column],
        "| Sales:", sales_data[row, column],
        "| Profit:", profit_data[row, column]
    )

Store: Bengaluru | Category: Electronics | Sales: 850000 | Profit: 210000
Store: Hyderabad | Category: Electronics | Sales: 780000 | Profit: 190000
Store: Chennai | Category: Electronics | Sales: 920000 | Profit: 220000
Store: Mumbai | Category: Electronics | Sales: 1050000 | Profit: 260000
Store: Pune | Category: Electronics | Sales: 690000 | Profit: 160000


In [40]:
# uestion 46: Underperforming Combinations
# A store-category combination is considered underperforming when:

# Sales are below ₹2,50,000
# Profit margin is below 25%
# Find all such combinations.
profit_margin = (profit_data / sales_data) * 100

condition = np.logical_and(
    sales_data < 250000,
    profit_margin < 25
)

rows, columns = np.where(condition)

for row, column in zip(rows, columns):
    print(
        "Store:", stores[row],
        "| Category:", categories[column],
        "| Sales:", sales_data[row, column],
        "| Cost:", cost_data[row, column],
        "| Profit:", profit_data[row, column],
        "| Margin:", round(profit_margin[row, column], 2), "%"
    )

Store: Pune | Category: Furniture | Sales: 225000 | Cost: 170000 | Profit: 55000 | Margin: 24.44 %


In [41]:
# Question 47: Category Performance Classification
# Create a new array that classifies every sales value as:

# "High" when sales are at least ₹5,00,000
# "Medium" when sales are between ₹2,50,000 and ₹4,99,999
# "Low" when sales are below ₹2,50,000
# Use np.where() or np.select().
conditions = [
    sales_data >= 500000,
    sales_data >= 250000
]

choices = [
    "High",
    "Medium"
]

performance = np.select(
    conditions,
    choices,
    default="Low"
)

print(performance)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis

In [21]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])


In [42]:
# Question 48: Target Comparison
# Compare every store’s category sales against sales_targets.

# Use NumPy broadcasting.
target_difference = sales_data - sales_targets

print(target_difference)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [43]:
# Question 49: Target Achievement Matrix
# Create a Boolean array where:

# True means the store achieved the category target
# False means the store failed to achieve the target
target_achieved = sales_data >= sales_targets

print(target_achieved)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [44]:
# Question 50: Target Achievement Count
# Calculate the number of categories in which each store achieved its target.
achievement_count = np.sum(target_achieved, axis=1)

for store, count in zip(stores, achievement_count):
    print(f"{store}: {count} categories")

Bengaluru: 1 categories
Hyderabad: 4 categories
Chennai: 2 categories
Mumbai: 6 categories
Pune: 0 categories


In [45]:
# Question 51: Best Target-Performing Store
# Find the store that achieved the highest number of category targets.
best_index = np.argmax(achievement_count)

print("Best store:", stores[best_index])
print("Targets achieved:", achievement_count[best_index])

Best store: Mumbai
Targets achieved: 6


In [46]:
# Question 52: Target Achievement by Category
# Calculate how many stores achieved the target for each product category.
category_achievement_count = np.sum(target_achieved, axis=0)

for category, count in zip(categories, category_achievement_count):
    print(f"{category}: {count} stores")

Electronics: 3 stores
Groceries: 2 stores
Clothing: 2 stores
Furniture: 2 stores
Beauty: 2 stores
Sports: 2 stores


In [48]:
# Question 53: Sales Target Variance
# Calculate the difference between actual sales and target sales for every store.

# Use:

# Variance = Actual Sales - Target Sales
variance = sales_data - sales_targets

print(variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [50]:
# Question 54: Percentage Above or Below Target
# Calculate the percentage variance from the target using:

# Percentage Variance =
# (Actual Sales - Target Sales) / Target Sales × 1
percentage_variance = (
    (sales_data - sales_targets) / sales_targets
) * 100

percentage_variance = np.round(percentage_variance, 2)

print(percentage_variance)
for i in range(len(stores)):
    print(f"\n{stores[i]}")

    for j in range(len(categories)):
        print(
            f"{categories[j]}: "
            f"{percentage_variance[i, j]}%"
        )

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]

Bengaluru
Electronics: 6.25%
Groceries: -6.67%
Clothing: -3.12%
Furniture: -8.33%
Beauty: -5.0%
Sports: -2.17%

Hyderabad
Electronics: -2.5%
Groceries: 2.22%
Clothing: -7.81%
Furniture: 3.33%
Beauty: 5.0%
Sports: 4.35%

Chennai
Electronics: 15.0%
Groceries: -13.33%
Clothing: 6.25%
Furniture: -13.33%
Beauty: -7.5%
Sports: -6.52%

Mumbai
Electronics: 31.25%
Groceries: 13.33%
Clothing: 17.19%
Furniture: 15.0%
Beauty: 25.0%
Sports: 26.09%

Pune
Electronics: -13.75%
Groceries: -10.0%
Clothing: -12.5%
Furniture: -25.0%
Beauty: -12.5%
Sports: -10.87%


In [51]:
# Question 55: Stores Missing Electronics Target
# Identify stores that failed to achieve the Electronics sales target.
electronics_target = sales_targets[0]

failed_electronics = sales_data[:, 0] < electronics_target

print(failed_electronics)
failed_stores = stores[failed_electronics]

print(failed_stores)

[False  True False False  True]
['Hyderabad' 'Pune']


In [ ]:
# Question 56: Stores Achieving All Targets
# Check whether any store achieved its target in all six product categories.

# Use np.all().
target_achieved

all_targets = np.all(target_achieved, axis=1)

print(all_targets)
stores_all_targets = stores[all_targets]

print(stores_all_targets)

In [53]:
# Question 57: Stores Achieving At Least One Target
# Identify stores that achieved at least one category target.

# Use np.any().
at_least_one = np.any(target_achieved, axis=1)

print(at_least_one)
stores_at_least_one = stores[at_least_one]

print(stores_at_least_one)

[ True  True  True  True False]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario

In [22]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [55]:
# Question 58: Discount Amount Matrix
# Calculate the discount amount for each store-category combination.

# Use broadcasting.
discount_amount = sales_data * discount_rates

print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [56]:
# Question 59: Sales After Discount
# Calculate the net sales value after applying the category-wise discounts
sales_after_discount = sales_data - discount_amount

print(sales_after_discount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [57]:
# Question 60: Profit After Discount
# Assuming costs remain unchanged, calculate the new profit after the discounts are applied.
profit_after_discount = sales_after_discount - cost_data

print(profit_after_discount)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [58]:
# Question 61: Profit Margin After Discount
# Calculate the new profit margin after applying discounts.
profit_margin_after_discount = (
    profit_after_discount / sales_after_discount
) * 100

profit_margin_after_discount = np.round(
    profit_margin_after_discount, 2
)

print(profit_margin_after_discount)

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [60]:
# Question 62: Loss-Making Transactions
# Check whether any store-category combination becomes loss-making after discounts.

# Display the affected store and category names.
loss_mask = profit_after_discount < 0

print(loss_mask)
rows, cols = np.where(loss_mask)

for r, c in zip(rows, cols):
    print(
        f"Store: {stores[r]}, "
        f"Category: {categories[c]}, "
        f"Profit: ₹{profit_after_discount[r, c]:,.2f}"
    )

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [61]:
# Question 63: Discount Impact
# Calculate how much total revenue the company loses because of the proposed discounts.
total_revenue_loss = np.sum(discount_amount)

print(f"Total revenue lost: ₹{total_revenue_loss:,.2f}")

Total revenue lost: ₹1,146,350.00


In [62]:
# Question 64: Store Most Affected by Discounts
# Identify the store that loses the highest amount of revenue due to discounts.
store_discount_loss = np.sum(discount_amount, axis=1)

best_affected_index = np.argmax(store_discount_loss)

print("Store:", stores[best_affected_index])
print(
    "Revenue lost:",
    f"₹{store_discount_loss[best_affected_index]:,.2f}"
)

Store: Mumbai
Revenue lost: ₹277,150.00


Part 11: Tax and Price Adjustment

In [23]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])


In [63]:
# Question 65: Tax Collection Matrix
# Calculate the tax collected on sales for each store and category.
tax_collection = sales_data * tax_rates

print(tax_collection)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [64]:
# Question 66: Sales Including Tax
# Calculate the final customer billing value after adding tax.
sales_including_tax = sales_data + tax_collection

print(sales_including_tax)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [65]:
# Question 67: Store-Wise Tax Collection
# Calculate the total tax collected by each store.
store_tax = np.sum(tax_collection, axis=1)

for store, tax in zip(stores, store_tax):
    print(f"{store}: ₹{tax:,.2f}")

Bengaluru: ₹321,900.00
Hyderabad: ₹321,200.00
Chennai: ₹331,800.00
Mumbai: ₹401,400.00
Pune: ₹274,650.00


In [66]:
# uestion 68: Category-Wise Tax Collection
# Calculate total tax collected for each category.
category_tax = np.sum(tax_collection, axis=0)

for category, tax in zip(categories, category_tax):
    print(f"{category}: ₹{tax:,.2f}")

Electronics: ₹772,200.00
Groceries: ₹109,250.00
Clothing: ₹192,000.00
Furniture: ₹254,700.00
Beauty: ₹181,800.00
Sports: ₹141,000.00


In [67]:
# Question 69: Highest Tax-Contributing Store
# Identify the store that contributes the highest tax amount.
highest_tax_index = np.argmax(store_tax)

print("Highest tax-contributing store:")
print("Store:", stores[highest_tax_index])
print("Tax:", f"₹{store_tax[highest_tax_index]:,.2f}")



Highest tax-contributing store:
Store: Mumbai
Tax: ₹401,400.00


Part 12: Array Modification

In [68]:
# Question 70: Updated Pune Electronics Sales
# The Pune store reports that its Electronics sales were entered incorrectly.

# Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

# Make the change in a copied array without modifying the original array.
updated_sales = sales_data.copy()

updated_sales[4, 0] = 740000

print(updated_sales)
print("Original:", sales_data[4, 0])
print("Updated:", updated_sales[4, 0])


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]
Original: 690000
Updated: 740000


In [69]:
# Question 71: Revised Beauty Cost
# Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

# Create an updated cost array.
updated_cost = cost_data.copy()

updated_cost[:, 4] = updated_cost[:, 4] * 0.92

print(updated_cost)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [70]:
# Question 72: Furniture Cost Increase
# Furniture costs increase by 12% for all stores.

# Update only the Furniture column.
updated_cost = cost_data.copy()

updated_cost[:, 3] = updated_cost[:, 3] * 1.12

print(updated_cost)

[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [71]:
# Question 73: Store Closure Simulation
# Assume the Pune store is temporarily closed.

# Remove Pune’s sales and cost data from the analysis using np.delete()
closed_sales = np.delete(sales_data, 4, axis=0)
closed_cost = np.delete(cost_data, 4, axis=0)

print("Sales after Pune closure:")
print(closed_sales)

print("\nCost after Pune closure:")
print(closed_cost)

Sales after Pune closure:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

Cost after Pune closure:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [73]:
# Question 74: Adding a New Store
# A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
# Add Delhi to both arrays using np.vstack().

# Also add "Delhi" to the stores array.

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

updated_sales = np.vstack((sales_data, delhi_sales))
updated_cost = np.vstack((cost_data, delhi_cost))
updated_stores = np.append(stores, "Delhi")

print(updated_stores)
print(updated_sales)
print(updated_cost)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


In [74]:
# Question 75: Adding a New Product Category
# SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
# Add the new category as a column using np.column_stack() or np.hstack().
updated_sales = np.column_stack(
    (sales_data, home_appliance_sales)
)

updated_cost = np.column_stack(
    (cost_data, home_appliance_cost)
)

updated_categories = np.append(
    categories,
    "Home Appliances"
)

print(updated_categories)
print(updated_sales)
print(updated_cost)

['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


Part 13: Sorting and Ranking

In [75]:
# Question 76: Sort Stores by Sales
# Sort stores in ascending order based on total sales.

# Display store names and sales totals.

sorted_indices = np.argsort(store_sales)

for i in sorted_indices:
    print(f"{stores[i]}: ₹{store_sales[i]:,.0f}")

Pune: ₹1,980,000
Bengaluru: ₹2,270,000
Hyderabad: ₹2,295,000
Chennai: ₹2,310,000
Mumbai: ₹2,820,000


In [78]:
rank_indices = np.argsort(store_profit)[::-1]

for rank, i in enumerate(rank_indices, start=1):
    print(
        f"Rank {rank}: {stores[i]} "
        f"₹{store_profit[i]:,.0f}"
    )

Rank 1: Mumbai ₹755,000
Rank 2: Hyderabad ₹610,000
Rank 3: Bengaluru ₹605,000
Rank 4: Chennai ₹600,000
Rank 5: Pune ₹505,000


In [79]:
# Question 78: Sort Categories by Revenue
# Sort product categories from highest to lowest total revenue.
category_sales = np.sum(sales_data, axis=0)
category_indices = np.argsort(category_sales)[::-1]

for i in category_indices:
    print(
        f"{categories[i]}: "
        f"₹{category_sales[i]:,.0f}"
    )

Electronics: ₹4,290,000
Groceries: ₹2,185,000
Clothing: ₹1,600,000
Furniture: ₹1,415,000
Sports: ₹1,175,000
Beauty: ₹1,010,000


In [80]:
# Question 79: Top Three Store-Category Sales
# Find the three highest individual sales values in the complete sales matrix.

# Display their:

# Sales value
# Store name
# Category name
flat_sales = sales_data.flatten()

top_three_flat_indices = np.argsort(flat_sales)[-3:][::-1]

for flat_index in top_three_flat_indices:

    row, col = np.unravel_index(
        flat_index,
        sales_data.shape
    )

    print(
        f"Store: {stores[row]}, "
        f"Category: {categories[col]}, "
        f"Sales: ₹{sales_data[row, col]:,.0f}"
    )

Store: Mumbai, Category: Electronics, Sales: ₹1,050,000
Store: Chennai, Category: Electronics, Sales: ₹920,000
Store: Bengaluru, Category: Electronics, Sales: ₹850,000


In [81]:
# Question 80: Bottom Three Profits
# Find the three lowest profit values in the profit matrix.
flat_profit = profit_data.flatten()

bottom_three_indices = np.argsort(flat_profit)[:3]

for flat_index in bottom_three_indices:

    row, col = np.unravel_index(
        flat_index,
        profit_data.shape
    )

    print(
        f"Store: {stores[row]}, "
        f"Category: {categories[col]}, "
        f"Profit: ₹{profit_data[row, col]:,.0f}"
    )


Store: Pune, Category: Furniture, Profit: ₹55,000
Store: Pune, Category: Sports, Profit: ₹60,000
Store: Chennai, Category: Sports, Profit: ₹60,000


Part 14: Statistical Analysis

In [82]:
# Question 81: Sales Statistics
# Calculate the following for the complete sales array:

# Minimum
# Maximum
# Mean
# Median
# Standard deviation
# Variance
# 25th percentile
# 50th percentile
# 75th percentile
print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))

print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


In [83]:
# Question 82: Store-Wise Standard Deviation
# Calculate the sales standard deviation for every store.

# Use this value to determine which store has the most variation between product categories.
store_std = np.std(sales_data, axis=1)

for i in range(len(stores)):
    print(stores[i], ":", store_std[i])
    highest_variation_index = np.argmax(store_std)

print("Store with highest variation:", stores[highest_variation_index])
print("Standard deviation:", store_std[highest_variation_index])

Bengaluru : 223059.53365762145
Hyderabad : 194502.57067709928
Chennai : 249265.58794453225
Mumbai : 271860.871280391
Pune : 177200.4514666935
Store with highest variation: Mumbai
Standard deviation: 271860.871280391


In [86]:
# Question 83: Category-Wise Standard Deviation
# Determine which product category has the highest variation in sales across stores.
category_std = np.std(sales_data, axis=0)

for i in range(len(categories)):
    print(categories[i], ":", category_std[i])
index = np.argmax(category_std)

print("Highest variation category:", categories[index])
print("Standard deviation:", category_std[index])


Electronics : 122539.78945632312
Groceries : 43312.815655415434
Clothing : 33911.64991562634
Furniture : 41303.75285612677
Beauty : 26570.660511172846
Sports : 29832.867780352597
Highest variation category: Electronics
Standard deviation: 122539.78945632312


In [87]:
# Question 84: Sales Above Company Average
# Calculate the company-wide average sales value.

# Count how many store-category sales values are above this average.
company_average = np.mean(sales_data)

print("Company average sales:", company_average)

above_average = sales_data > company_average
count = np.sum(above_average)

print("Number of sales values above company average:", count)

Company average sales: 389166.6666666667
Number of sales values above company average: 10


In [88]:
# Question 85: Outlier Detection
# Treat any sales value greater than:

# Mean + 1.5 × Standard Deviation
# as a high-value outlier.

# Identify all such sales values.
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

threshold = mean_sales + (1.5 * std_sales)

outlier_mask = sales_data > threshold

print("Outlier threshold:", threshold)
print("Outlier values:")
print(sales_data[outlier_mask])

locations = np.argwhere(outlier_mask)

for row, col in locations:
    print(
        stores[row],
        "|",
        categories[col],
        "|",
        sales_data[row, col]
    )



Outlier threshold: 734650.4759833985
Outlier values:
[ 850000  780000  920000 1050000]
Bengaluru | Electronics | 850000
Hyderabad | Electronics | 780000
Chennai | Electronics | 920000
Mumbai | Electronics | 1050000


Part 15: Reshaping and Transformation

In [89]:
# Question 86: Flatten Sales Data
# Convert the two-dimensional sales array into a one-dimensional array using:

# flatten()
# ravel()
# Explain the difference between the two methods.
flat_sales = sales_data.flatten()
ravel_sales = sales_data.ravel()

print("Flatten:")
print(flat_sales)

print("\nRavel:")
print(ravel_sales)

print("\nFlatten shape:", flat_sales.shape)
print("Ravel shape:", ravel_sales.shape)

Flatten:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Ravel:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Flatten shape: (30,)
Ravel shape: (30,)


In [90]:
# Question 87: Reshape Sales Data
# Reshape the 5 × 6 sales array into:

# 3 × 10
# 10 × 3
# 2 × 15
# 15 × 2
# Verify that no data is lost.
sales_3x10 = sales_data.reshape(3, 10)
sales_10x3 = sales_data.reshape(10, 3)
sales_2x15 = sales_data.reshape(2, 15)
sales_15x2 = sales_data.reshape(15, 2)

print("3 × 10:")
print(sales_3x10)

print("\n10 × 3:")
print(sales_10x3)

print("\n2 × 15:")
print(sales_2x15)

print("\n15 × 2:")
print(sales_15x2)

print("\nOriginal number of elements:", sales_data.size)
print("3 × 10 elements:", sales_3x10.size)
print("10 × 3 elements:", sales_10x3.size)
print("2 × 15 elements:", sales_2x15.size)
print("15 × 2 elements:", sales_15x2.size)



3 × 10:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]

10 × 3:
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]

2 × 15:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]

15 × 2:
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  51000

In [91]:
# Question 88: Transpose Sales Data
# Transpose the sales array so that:

# Rows represent product categories
# Columns represent stores
# Display the new shape.
sales_transposed = sales_data.T

print("Original shape:", sales_data.shape)
print("New shape:", sales_transposed.shape)

print(sales_transposed)




Original shape: (5, 6)
New shape: (6, 5)
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


In [92]:
# Question 89: Combined Sales and Cost Array
# Stack sales_data and cost_data vertically.

# Display the resulting shape.
combined_data = np.vstack((sales_data, cost_data))

print("Combined array:")
print(combined_data)

print("Combined shape:", combined_data.shape)

Combined array:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Combined shape: (10, 6)


In [93]:
# Question 90: Store-Level Combined Data
# Create a three-dimensional array where:

# First layer contains sales data
# Second layer contains cost data
# Use np.stack().

# Display the shape of the new array.
combined_3d = np.stack((sales_data, cost_data))

print("3D array:")
print(combined_3d)

print("Shape:", combined_3d.shape)

print("\nSales layer:")
print(combined_3d[0])

print("\nCost layer:")
print(combined_3d[1])

3D array:
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Shape: (2, 5, 6)

Sales layer:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost layer:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 1

Part 16: Missing Data Scenario

In [26]:
# The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])


In [94]:
# Question 91: Missing Value Detection
# Find:

# Total number of missing values
# Location of missing values
# Stores and categories containing missing values
missing_mask = np.isnan(sales_with_missing)

print("Total missing values:", np.sum(missing_mask))

locations = np.argwhere(missing_mask)

for row, col in locations:
    print(
        "Store:", stores[row],
        "| Category:", categories[col]
    )

Total missing values: 4
Store: Bengaluru | Category: Clothing
Store: Hyderabad | Category: Furniture
Store: Mumbai | Category: Groceries
Store: Pune | Category: Beauty


In [95]:
# Question 92: Replace Missing Values with Zero
# Replace all missing sales values with zero.
sales_zero = np.nan_to_num(sales_with_missing, nan=0)

print(sales_zero)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [96]:
# Question 93: Replace with Company Average
# Replace missing values with the overall average of available sales values.

# Use np.nanmean().
average_sales = np.nanmean(sales_with_missing)

sales_average = np.where(
    np.isnan(sales_with_missing),
    average_sales,
    sales_with_missing
)

print(sales_average)

[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [97]:
# Question 94: Replace with Category Average
# Replace each missing value with the average sales value of its respective product category.
sales_category_average = sales_with_missing.copy()

for col in range(sales_category_average.shape[1]):
    category_average = np.nanmean(sales_category_average[:, col])

    missing = np.isnan(sales_category_average[:, col])

    sales_category_average[missing, col] = category_average

print(sales_category_average)

[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [98]:
# Question 95: Missing Value Impact
# Compare total sales before and after replacing missing values with zero.
original_total = np.nansum(sales_with_missing)

sales_zero = np.nan_to_num(sales_with_missing, nan=0)

new_total = np.sum(sales_zero)

print("Total sales before replacement:", original_total)
print("Total sales after replacing missing values with zero:", new_total)
print("Difference:", original_total - new_total)

Total sales before replacement: 10370000.0
Total sales after replacing missing values with zero: 10370000.0
Difference: 0.0


Part 17: Conditional Business Decisions

In [101]:
# Question 96: Store Performance Labels
# Classify each store based on total sales:

# "Excellent": Total sales above ₹28,00,000
# "Good": Total sales between ₹24,00,000 and ₹28,00,000
# "Needs Improvement": Total sales below ₹24,00,000
# Use np.select().
store_sales = np.sum(sales_data, axis=1)

conditions = [
    store_sales > 2800000,
    (store_sales >= 2400000) & (store_sales <= 2800000),
    store_sales < 2400000
]

labels = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

performance = np.select(
    conditions,
    labels,
    default="Unknown"
)

for i in range(len(stores)):
    print(stores[i], ":", store_sales[i], "->", performance[i])

Bengaluru : 2270000 -> Needs Improvement
Hyderabad : 2295000 -> Needs Improvement
Chennai : 2310000 -> Needs Improvement
Mumbai : 2820000 -> Excellent
Pune : 1980000 -> Needs Improvement


In [102]:
# Question 97: Profitability Classification
# Classify each store-category combination as:

# "Highly Profitable": Profit above ₹2,00,000
# "Profitable": Profit between ₹1,00,000 and ₹2,00,000
# "Low Profit": Profit below ₹1,00,000
# "Loss": Profit below zero
conditions = [
    profit_data < 0,
    (profit_data >= 0) & (profit_data < 100000),
    (profit_data >= 100000) & (profit_data <= 200000),
    profit_data > 200000
]

labels = [
    "Loss",
    "Low Profit",
    "Profitable",
    "Highly Profitable"
]

classification = np.select(
    conditions,
    labels,
    default="Unknown"
)

print(classification)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [103]:
# Question 98: Expansion Recommendation
# A store is eligible for expansion when:

# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores.
store_sales = np.sum(sales_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_margin = (store_profit / store_sales) * 100

eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_margin > 25)
)

print("Eligible Stores:")

for i in np.where(eligible)[0]:
    print(stores[i])

Eligible Stores:
Mumbai


In [104]:
# Question 99: Category Promotion Recommendation
# A product category should receive additional promotion when:

# Average sales are below ₹3,00,000
# Profit margin is above 25%
# Identify the categories that satisfy these conditions.
category_sales = np.sum(sales_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

average_sales = np.mean(sales_data, axis=0)
category_margin = (category_profit / category_sales) * 100

condition = (
    (average_sales < 300000) &
    (category_margin > 25)
)

print("Categories for Promotion:")

for i in np.where(condition)[0]:
    print(categories[i])



Categories for Promotion:
Furniture
Beauty
Sports


In [105]:
# uestion 100: Cost Optimization Recommendation
# Find store-category combinations where:

# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.
profit_margin = (profit_data / sales_data) * 100

condition = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

locations = np.argwhere(condition)

for row, col in locations:
    print(
        "Store:", stores[row],
        "| Category:", categories[col],
        "| Cost:", cost_data[row, col],
        "| Profit Margin:", round(profit_margin[row, col], 2)
    )

Store: Bengaluru | Category: Electronics | Cost: 640000 | Profit Margin: 24.71
Store: Hyderabad | Category: Electronics | Cost: 590000 | Profit Margin: 24.36
Store: Hyderabad | Category: Groceries | Cost: 350000 | Profit Margin: 23.91
Store: Chennai | Category: Electronics | Cost: 700000 | Profit Margin: 23.91
Store: Chennai | Category: Groceries | Cost: 295000 | Profit Margin: 24.36
Store: Mumbai | Category: Electronics | Cost: 790000 | Profit Margin: 24.76
Store: Mumbai | Category: Groceries | Cost: 390000 | Profit Margin: 23.53
Store: Pune | Category: Electronics | Cost: 530000 | Profit Margin: 23.19
Store: Pune | Category: Groceries | Cost: 310000 | Profit Margin: 23.46


Part 18: Inventory Scenario

In [27]:
# Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])


In [106]:
# Question 101: Closing Stock
# Calculate closing stock using:

# Closing Stock = Opening Stock - Units Sold

closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [107]:
# Question 102: Low-Stock Identification
# Identify store-category combinations where closing stock is below 30 units.
low_stock = closing_stock < 30

locations = np.argwhere(low_stock)

for row, col in locations:
    print(
        "Store:", stores[row],
        "| Category:", categories[col],
        "| Closing Stock:", closing_stock[row, col]
    )

Store: Bengaluru | Category: Electronics | Closing Stock: 25
Store: Bengaluru | Category: Furniture | Closing Stock: 25
Store: Hyderabad | Category: Electronics | Closing Stock: 25
Store: Hyderabad | Category: Furniture | Closing Stock: 25
Store: Chennai | Category: Electronics | Closing Stock: 25
Store: Chennai | Category: Furniture | Closing Stock: 25
Store: Mumbai | Category: Electronics | Closing Stock: 25
Store: Pune | Category: Electronics | Closing Stock: 25
Store: Pune | Category: Furniture | Closing Stock: 20


In [108]:
# Question 103: Stock Availability Percentage
# Calculate the percentage of opening stock that remains unsold.

stock_percentage = (closing_stock / opening_stock) * 100

print(np.round(stock_percentage, 2))


[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [109]:
# Question 104: Fast-Moving Products
# A product is considered fast-moving when more than 80% of its opening stock has been sold.

# Identify fast-moving store-category combinations.
sold_percentage = (units_sold / opening_stock) * 100

fast_moving = sold_percentage > 80

locations = np.argwhere(fast_moving)

for row, col in locations:
    print(
        "Store:", stores[row],
        "| Category:", categories[col],
        "| Sold:", round(sold_percentage[row, col], 2), "%"
    )

Store: Bengaluru | Category: Groceries | Sold: 84.44 %
Store: Hyderabad | Category: Groceries | Sold: 84.0 %
Store: Hyderabad | Category: Clothing | Sold: 82.14 %
Store: Chennai | Category: Electronics | Sold: 80.77 %
Store: Chennai | Category: Groceries | Sold: 83.33 %
Store: Chennai | Category: Clothing | Sold: 84.38 %
Store: Mumbai | Category: Electronics | Sold: 83.33 %
Store: Mumbai | Category: Groceries | Sold: 85.45 %
Store: Mumbai | Category: Clothing | Sold: 84.29 %
Store: Pune | Category: Groceries | Sold: 82.5 %


In [110]:
# Question 105: Category-Wise Units Sold
# Calculate the total units sold for each product category.
sold_percentage = (units_sold / opening_stock) * 100

fast_moving = sold_percentage > 80

locations = np.argwhere(fast_moving)

for row, col in locations:
    print(
        "Store:", stores[row],
        "| Category:", categories[col],
        "| Sold:", round(sold_percentage[row, col], 2), "%"
    )

Store: Bengaluru | Category: Groceries | Sold: 84.44 %
Store: Hyderabad | Category: Groceries | Sold: 84.0 %
Store: Hyderabad | Category: Clothing | Sold: 82.14 %
Store: Chennai | Category: Electronics | Sold: 80.77 %
Store: Chennai | Category: Groceries | Sold: 83.33 %
Store: Chennai | Category: Clothing | Sold: 84.38 %
Store: Mumbai | Category: Electronics | Sold: 83.33 %
Store: Mumbai | Category: Groceries | Sold: 85.45 %
Store: Mumbai | Category: Clothing | Sold: 84.29 %
Store: Pune | Category: Groceries | Sold: 82.5 %


In [111]:
# Question 106: Store-Wise Units Sold
# Calculate total units sold by each store.
store_units_sold = np.sum(units_sold, axis=1)

for i in range(len(stores)):
    print(stores[i], ":", store_units_sold[i])

Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


In [112]:
# Question 107: Best Store by Unit Sales
# Identify the store that sold the highest total number of units.
store_units_sold = np.sum(units_sold, axis=1)

index = np.argmax(store_units_sold)

print("Best Store:", stores[index])
print("Units Sold:", store_units_sold[index])

Best Store: Mumbai
Units Sold: 1390


In [113]:
# Question 108: Reorder Requirement
# A store should reorder a category when closing stock is below 25 units.

# Create a Boolean reorder matrix.
reorder_matrix = closing_stock < 25

print(reorder_matrix)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [114]:
# Question 109: Reorder Quantity
# Assume each category must maintain 100 units after reordering.

# Calculate reorder quantities only for combinations where closing stock is below 25.

# For all other combinations, return zero.
reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)

print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

In [115]:
# Question 110: Cumulative Store Sales
# Calculate cumulative category sales for each store using np.cumsum().
cumulative_store_sales = np.cumsum(sales_data, axis=1)

print(cumulative_store_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [116]:
# Question 111: Cumulative Company Sales
# Flatten the sales array and calculate cumulative company sales.
flat_sales = sales_data.flatten()

cumulative_company_sales = np.cumsum(flat_sales)

print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [117]:
# Question 112: Sales Difference Between Categories
# Calculate the difference between consecutive category sales for each store using np.diff().
sales_difference = np.diff(sales_data, axis=1)

print(sales_difference)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [118]:
# Question 113: Unique Sales Values
# Find all unique sales values in sales_data.

# Also count the frequency of each value.
unique_values, frequency = np.unique(
    sales_data,
    return_counts=True
)

print("Unique Sales Values:")
print(unique_values)

print("\nFrequency:")
print(frequency)

Unique Sales Values:
[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]

Frequency:
[1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [119]:
# Question 114: Search for Specific Sales
# Check whether the value ₹4,20,000 exists in the sales array.

# Return its location.
value = 420000

locations = np.argwhere(sales_data == value)

if locations.size > 0:
    print("Value exists")

    for row, col in locations:
        print(
            "Store:", stores[row],
            "| Category:", categories[col]
        )
else:
    print("Value does not exist")



Value exists
Store: Bengaluru | Category: Groceries


In [120]:
# Question 115: Compare Sales and Cost
# Create a Boolean array showing whether sales are greater than cost for every combination.

# Verify whether all combinations are profitable using np.all().
sales_greater_than_cost = sales_data > cost_data

print(sales_greater_than_cost)

all_profitable = np.all(sales_greater_than_cost)

print("All combinations profitable:", all_profitable)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All combinations profitable: True


In [121]:
# Question 116: Clip Profit Values
# For reporting purposes, management wants profit values limited to:

# Minimum: ₹75,000
# Maximum: ₹2,50,000
# Use np.clip() to create a reporting profit array.
reporting_profit = np.clip(
    profit_data,
    75000,
    250000
)

print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [122]:
# Question 117: Normalize Sales Data
# Normalize all sales values using min-max normalization:

# Normalized Sales =
# (Sales - Minimum Sales) / (Maximum Sales - Minimum
minimum_sales = np.min(sales_data)
maximum_sales = np.max(sales_data)

normalized_sales = (
    (sales_data - minimum_sales) /
    (maximum_sales - minimum_sales)
)

print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [123]:
# Question 118: Standardize Sales Data
# Standardize sales using:

# Standardized Sales =
# (Sales - Mean Sales) / Standard Deviation

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

standardized_sales = (
    (sales_data - mean_sales) /
    std_sales
)

print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [124]:
# Question 119: Round Values
# Convert profit margin values into:

# Two decimal places
# Nearest whole number
# Floor values
# Ceiling values
two_decimal = np.round(profit_margin, 2)

nearest_whole = np.round(profit_margin)

floor_values = np.floor(profit_margin)

ceiling_values = np.ceil(profit_margin)

print("Two Decimal Places:")
print(two_decimal)

print("\nNearest Whole Number:")
print(nearest_whole)

print("\nFloor Values:")
print(floor_values)

print("\nCeiling Values:")
print(ceiling_values)

Two Decimal Places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest Whole Number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor Values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling Values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [125]:
# Question 120: Save and Load Data
# Save the following arrays as NumPy binary files:

# sales_data.npy
# cost_data.npy
# profit_data.npy
# Load them back and verify that the loaded arrays are equal to the original arrays.

np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

print("Sales equal:", np.array_equal(sales_data, loaded_sales))
print("Cost equal:", np.array_equal(cost_data, loaded_cost))
print("Profit equal:", np.array_equal(profit_data, loaded_profit))


Sales equal: True
Cost equal: True
Profit equal: True


In [126]:
# Part 20: Final Retail Analytics Project
# Prepare a complete NumPy-based retail performance report.

# Your report must contain the following information:

# Company Summary
# Total company sales
# Total company cost
# Total company profit
# Overall company profit margin
# Average transaction value
# Highest individual sales value
# Lowest individual sales value
# Store Summary
# For every store, display:

# Total sales
# Total cost
# Total profit
# Profit margin
# Number of category targets achieved
# Total units sold
# Expansion eligibility
# Category Summary
# For every category, display:

# Total sales
# Total cost
# Total profit
# Profit margin
# Average sales
# Number of stores achieving the target
# Total units sold
# Management Recommendations
# Based on the analysis, identify:

# Best-performing store
# Lowest-performing store
# Most profitable category
# Lowest-profit category
# Store recommended for expansion
# Category requiring additional marketing
# Store-category combinations needing cost optimization
# Store-category combinations requiring inventory reorder
# Expected Final Output Format
# SMARTMART RETAIL PERFORMANCE REPORT
# ===================================

# COMPANY SUMMARY
# ---------------
# Total Sales:
# Total Cost:
# Total Profit:
# Overall Profit Margin:

# BEST-PERFORMING STORE
# ---------------------
# Store:
# Sales:
# Cost:
# Profit:
# Profit Margin:

# MOST PROFITABLE CATEGORY
# ------------------------
# Category:
# Sales:
# Cost:
# Profit:
# Profit Margin:

# EXPANSION RECOMMENDATIONS
# -------------------------
# Eligible Stores:

# COST OPTIMIZATION
# -----------------
# Store:
# Category:
# Cost:
# Profit Margin:

# INVENTORY REORDER
# -----------------
# Store:
# Category:
# Closing Stock:
# Reorder Quantity:

import numpy as np

# ============================================================
# DATA
# ============================================================

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

# ============================================================
# CORE CALCULATIONS
# ============================================================

profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_margin = (store_profit / store_sales) * 100

category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)
category_margin = (category_profit / category_sales) * 100
category_average_sales = np.mean(sales_data, axis=0)

target_achieved = sales_data >= sales_targets
store_target_count = np.sum(target_achieved, axis=1)
category_target_count = np.sum(target_achieved, axis=0)

closing_stock = opening_stock - units_sold
reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)
reorder_needed = closing_stock < 25

# ============================================================
# HELPERS
# ============================================================

def money(value):
    return f"₹{value:,.2f}"

def show_pair(title, value):
    print(f"{title}: {value}")

# ============================================================
# COMPANY SUMMARY
# ============================================================

total_company_sales = np.sum(sales_data)
total_company_cost = np.sum(cost_data)
total_company_profit = np.sum(profit_data)
overall_company_profit_margin = (total_company_profit / total_company_sales) * 100
average_transaction_value = np.mean(sales_data)
highest_individual_sales_value = np.max(sales_data)
lowest_individual_sales_value = np.min(sales_data)

# ============================================================
# MANAGEMENT RECOMMENDATIONS
# ============================================================

best_store_index = np.argmax(store_profit)
lowest_store_index = np.argmin(store_profit)

most_profitable_category_index = np.argmax(category_profit)
lowest_profit_category_index = np.argmin(category_profit)

expansion_eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_margin > 25)
)

promotion_category = (
    (category_average_sales < 300000) &
    (category_margin > 25)
)

cost_optimization_mask = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

reorder_mask = closing_stock < 25

# ============================================================
# FINAL REPORT
# ============================================================

print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")

print("\nCOMPANY SUMMARY")
print("---------------")
show_pair("Total Sales", money(total_company_sales))
show_pair("Total Cost", money(total_company_cost))
show_pair("Total Profit", money(total_company_profit))
show_pair("Overall Profit Margin", f"{overall_company_profit_margin:.2f}%")
show_pair("Average Transaction Value", money(average_transaction_value))
show_pair("Highest Individual Sales Value", money(highest_individual_sales_value))
show_pair("Lowest Individual Sales Value", money(lowest_individual_sales_value))

print("\nSTORE SUMMARY")
print("-------------")
for i in range(len(stores)):
    show_pair("Store", stores[i])
    show_pair("Total Sales", money(store_sales[i]))
    show_pair("Total Cost", money(store_cost[i]))
    show_pair("Total Profit", money(store_profit[i]))
    show_pair("Profit Margin", f"{store_margin[i]:.2f}%")
    show_pair("Number of Category Targets Achieved", int(store_target_count[i]))
    show_pair("Total Units Sold", int(np.sum(units_sold[i])))
    show_pair("Expansion Eligibility", "Yes" if expansion_eligible[i] else "No")
    print()

print("\nCATEGORY SUMMARY")
print("----------------")
for i in range(len(categories)):
    show_pair("Category", categories[i])
    show_pair("Total Sales", money(category_sales[i]))
    show_pair("Total Cost", money(category_cost[i]))
    show_pair("Total Profit", money(category_profit[i]))
    show_pair("Profit Margin", f"{category_margin[i]:.2f}%")
    show_pair("Average Sales", money(category_average_sales[i]))
    show_pair("Number of Stores Achieving Target", int(category_target_count[i]))
    show_pair("Total Units Sold", int(np.sum(units_sold[:, i])))
    print()

print("\nMANAGEMENT RECOMMENDATIONS")
print("--------------------------")
show_pair("Best-Performing Store", stores[best_store_index])
show_pair("Lowest-Performing Store", stores[lowest_store_index])
show_pair("Most Profitable Category", categories[most_profitable_category_index])
show_pair("Lowest-Profit Category", categories[lowest_profit_category_index])

print("\nStore Recommended for Expansion:")
for i in np.where(expansion_eligible)[0]:
    print(f"- {stores[i]}")

print("\nCategory Requiring Additional Marketing:")
for i in np.where(promotion_category)[0]:
    print(f"- {categories[i]}")

print("\nStore-Category Combinations Needing Cost Optimization:")
for row, col in np.argwhere(cost_optimization_mask):
    print(
        f"- {stores[row]} | {categories[col]} | "
        f"Cost: {money(cost_data[row, col])} | "
        f"Profit Margin: {profit_margin[row, col]:.2f}%"
    )

print("\nStore-Category Combinations Requiring Inventory Reorder:")
for row, col in np.argwhere(reorder_mask):
    print(
        f"- {stores[row]} | {categories[col]} | "
        f"Closing Stock: {int(closing_stock[row, col])} | "
        f"Reorder Quantity: {int(reorder_quantity[row, col])}"
    )



SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: ₹11,675,000.00
Total Cost: ₹8,600,000.00
Total Profit: ₹3,075,000.00
Overall Profit Margin: 26.34%
Average Transaction Value: ₹389,166.67
Highest Individual Sales Value: ₹1,050,000.00
Lowest Individual Sales Value: ₹175,000.00

STORE SUMMARY
-------------
Store: Bengaluru
Total Sales: ₹2,270,000.00
Total Cost: ₹1,665,000.00
Total Profit: ₹605,000.00
Profit Margin: 26.65%
Number of Category Targets Achieved: 1
Total Units Sold: 1110
Expansion Eligibility: No

Store: Hyderabad
Total Sales: ₹2,295,000.00
Total Cost: ₹1,685,000.00
Total Profit: ₹610,000.00
Profit Margin: 26.58%
Number of Category Targets Achieved: 4
Total Units Sold: 1175
Expansion Eligibility: No

Store: Chennai
Total Sales: ₹2,310,000.00
Total Cost: ₹1,710,000.00
Total Profit: ₹600,000.00
Profit Margin: 25.97%
Number of Category Targets Achieved: 2
Total Units Sold: 1095
Expansion Eligibility: No

Store: Mumbai
Total Sales: ₹2,820,000.00
To